name: Build

on:
  push:
    branches: [ "8.2-alpine" ]
  pull_request:
    branches: [ "8.2-alpine" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
